### ISSUE TITLE
💡 RFC: Better closing brackets

### ISSUE THREAD

**Issue by mrcaidev** [withastro/prettier-plugin-astro#279]
### Background & Motivation

When using libraries like Tailwind, it's a common scenario that we have a long, long line of class names in HTML (or template, in Astro). When using `prettier-plugin-astro`, I notice the formatting output looks like this:

```astro
<span class="hidden md:inline font-bold text-xl group-hover:text-highlight"
  >@mrcaidev/hooks</span
>
```

And I think it looks a little weird to always put that `>` on a new line, as it would confuse the "tag part" and the contained "text part".

### Possible solutions

I think native Prettier has a nice solution already. When I was writing Next.js, I often see this kind of output:

```tsx
<Link className="px-2 py-1 font-bold text-xl hover:text-highlight">
  some text content here
</Link>
```

Text content has its own new line, so that it would't look messed up with tags. And the closing tag is on one line, rather than being split up into two lines.

And if we have many attributes:

```tsx
<Link
  href="/"
  hrefLang="en"
  className="px-2 py-1 font-bold text-xl hover:text-highlight"
>
  some text content here
</Link>
```

### Alternatives considered

/

### Risks, downsides, and/or tradeoffs

The closing bracket of `Link` in Scenario 2 takes up an entire new line, so it will probably add many new lines to the whole file.

But I think it will overall look better than the current compact style.

### Detailed Design

I think the code involved lives in [`src/printer/index.ts`](https://github.com/withastro/prettier-plugin-astro/blob/main/src/printer/index.ts#L152), around line 152 - 238.

### Help make it happen!

- [ ] I am willing to submit a PR to implement this change.
- [X] I am willing to submit a PR to implement this change, but would need some guidance.
- [ ] I am not willing to submit a PR to implement this change.

**Comment by Princesseuh** [comment]
Hello! The reason why the ending bracket is on a newline is due to whitespace sensitivity. The same behaviour happens inside .html files, as shown [here](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAzgBwIZQARgA2266AvADogAWAlgCb0J4C29StUhnceAZtBgBaAEYRC9PPAAew6YTwBzAE4QArpiHUIANzjKkM4XUXVupmFQB8AARbKw2BnB0B6bRADW6VK6y4KKCsQABoQCEwYWmh0ZFBsZVUAdwAFBIRYlGxCJOwAT1iwkWVsME84GABlbBY4ABkeZD5s9DgikrKKypwwTkVkGGU1NpA4FhE4Rkm63EU1bEU4ADEIZRZsGCiofqy1GAhQmhgWQgB1Onh-MDhKjNoonXu85HBSQ85W5RgUksV1ppaIwAVuhpJU+oQ4ABFNQQeAAwitMI4ZSfF7UY6EQ6YZScGCnBgwajIAAcAAZkapWqcSpgXji4J89IcAI6w+A-CKZEAkIRQOCTSaHZRwNm0EU-Bb-JDNREjVosWgDIbyiHQ9lwBFIkAwbAiAn0InIABMYUGTm42wAwhAWNLRugAKyHNStAAqesysu1OmGAEkoExYJUwLjIgBBQOVGB5SFauAAXwTQA)

JSX doesn't have this behaviour because it doesn't care much about whitespace (hence why you need to do `{" "}` to insert whitespace), but in Astro (or HTML, Svelte etc) files it's relevant.
