### ISSUE TITLE
🐛 BUG: Properties spreading doesn't format inside function arguments or object.

### ISSUE THREAD

**Issue by JulianCataldo** [withastro/prettier-plugin-astro#318]
### Describe the Bug

<img width="569" alt="Screenshot 2023-01-23 at 12 25 52" src="https://user-images.githubusercontent.com/603498/214028335-c38b50a6-38dc-42b4-8f6c-b69d9fd916b7.png">

<img width="567" alt="Screenshot 2023-01-23 at 12 26 55" src="https://user-images.githubusercontent.com/603498/214028567-a026e2c4-addf-457c-aa48-8e9229016ec0.png">

Adjacent bug, not related but worth noticing:

<img width="564" alt="Screenshot 2023-01-23 at 12 27 25" src="https://user-images.githubusercontent.com/603498/214028652-f33ba244-df1b-4082-9b20-78888552193f.png">

Each time you type a full stop, it will disrupt the workflow by triggering auto-completion popup which will override next dots input. You have to type :

<kbd>.</kbd>, <kbd>ESC</kbd>, <kbd>.</kbd>, <kbd>ESC</kbd>,…

**Comment by Princesseuh** [comment]
Hello, thank you for reporting this issue! It's an interesting one, this happens because spread attributes are considered different from expression attributes (which, admittedly, I'm not sure why. Could be a compiler-internal thing), as such they're read as text instead of JavaScript to format. 

I'll check if it's safe to consider spread attributes to just be JavaScript all the time and report back!
